name: Bundle Source

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Bundle src/*.js
        run: node ./scripts/merge.js
          echo test, and deploy your project.
