name: pack

on:
  push:
    branches:
      - master

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Copy files into separate directory
        run: mkdir ytdwl && cp -vr manifest.json src/ js/ icons/ html/ ytdwl/

      - name: Package to zip
        uses: papeloto/action-zip@v1
        with:
          files: ytdwl/
          dest: ytdwl.zip
        
      - name: Get tag name
        run: echo "::set-output name=version::$(node ./scripts/get-tag.js)"
        id: version_tag

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "ytdwl.zip"
          tag: ${{ steps.version_tag.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
