name: test

on: [ push ]

jobs:
  test-extension:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ts
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build source
        run: npm run build

  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci
        
      - name: Build frontend
        run: npm run build

      - name: Test
        run: npm run test